model: "efficientnet_b0"

num_classes: 2
sched: cosine
epochs: 100
warmup_epochs: 10
# lr: 0.1
# reprob: 0.5
# remode: pixel
batch_size: 128
j: 4
pretrained: True
# weight_decay: 0.00002

# aug parameter

# root: /media/ubuntu/Date12/TableStruct/new_data/wire_or_not
data_dir: /media/ubuntu/Date12/TableStruct/new_data/test_A_jpg480max
dataset: torch/image_folder
# dataset_download: True
